board client test
Signed-off-by: bennof <b.falkner@gmail.com>

diff --git a/edo365board-client/DEBIAN/postinst b/edo365board-client/DEBIAN/postinst
--- a/edo365board-client/DEBIAN/postinst
+++ b/edo365board-client/DEBIAN/postinst
@@ -1,1 +1,56 @@
 #!/bin/sh
+set -e
+echo  "Configure edo365board client ..."
+
+# read parameter
+pread() {
+    if test -z "$2" ; then echo "Enter $1: "; read RET;
+    elif test "$2" = "passwd" ; then echo "Enter $1: "; stty -echo; read RET; stty echo;
+    else echo "Enter $1 (default: $2): "; read RET; test -z "$RET" && RET=$2;
+    fi
+}
+# error
+die() { echo "ERROR: $1" ; exitr 1; }
+
+if test -e "/etc/edo365board_client.conf"; then 
+    while read -r SERVERNAME USER; 
+        do C_EXIST=true; 
+    done < "/etc/edo365board.conf"
+else 
+    pread "enter server address" "http://loacalhost:80/"
+    SERVERNAME="$RET"
+    pread "username" "board_client_user"
+    USER="$RET"
+
+    i=0;
+    while test "$i" -lt "5"; do
+        pread "password" passwd
+        PASSWD="$RET"
+        pread "confirm password" passwd
+        PASSWD2="$RET"
+        if test "$PASSWD" = "$PASSWD2"; then
+            break;
+        fi
+        echo "Does not match, retry ($i).";
+        i=$(expr "$i" + "1");
+    done;
+    test "$i" -eq "5" && exit 1;
+fi
+
+# Create User
+UHOME=/home/$USER
+useradd --home $UHOME $USER  || true;
+echo "#!/bin/sh" > $UHOME/.xinitrc
+echo "chromium --kiosk $SERVERNAME" >> $UHOME/.xinitrc
+echo "if test -z \"\$DISPLAY\" && test \"\$(tty)\" = \"/dev/tty1\"; then" >> $UHOME/.profile
+echo "exec xinit" >> $UHOME/.profile
+echo "fi" >> $UHOME/.profile
+
+# Enable autologin
+cat /etc/systemd/system/getty.target.wants/getty@tty1.service | sed -e "s!*ExecStart=*!ExecStart=-/sbin/agetty -a $USER %I \$TERM!g" > /etc/systemd/system/getty.target.wants/getty@tty1_autologin.service;
+cat /etc/systemd/system/getty.target.wants/getty@tty1.service > cat /etc/systemd/system/getty.target.wants/getty@tty1.service.old
+rm -f /etc/systemd/system/getty.target.wants/getty@tty1.service 
+ln -s /etc/systemd/system/getty.target.wants/getty@tty1_autologin.service /etc/systemd/system/getty.target.wants/getty@tty1.service
+
+# Save config
+echo "$SERVERNAME $USER"> "/etc/edo365board_client.conf"
